apiVersion: v1
kind: Service
metadata:
  name: {{ include "online-boutique-service.fullname" . }}
  labels:
    {{- include "online-boutique-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "online-boutique-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}

